# 表示当前工作流的名字是什么
name: Android CI

# 表示当前工作流在什么情况下被触发
# 当我们在main分支push了代码，或者提了一个新的PR，要合并到main分支时，此时就会触发这个工作流
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# 指的是当前任务列表。我们只有一个任务，名为 build，当然也可以使用 name: 进行重命名
jobs:
  build:
    # 指定当前任务运行的环境。在 ubuntu-latest 系统下运行
    runs-on: ubuntu-latest

    # 指定当前任务的步骤列表。比如当前示例中，我们有多个任务，分别如下：
    # 拉代码
    # 设置 jdk 与 Gradle 环境
    # 为 Gradle 设置运行权限
    # 执行 Gradle 命令: build
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      # run: ./gradlew build
      run: ./gradlew assembleDebug
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
      - name: Install fir-cli
        continue-on-error: true
        run: gem install fir-cli
      - name: Upload to Fir
        continue-on-error: true
        id: fir-upload
        run: |
          fir login $FIR_TOKEN
          fir publish $OUTPUT_DIR/*.apk
